name: Typecheck

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Download latest nightly Juvix binary
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: anoma/juvix-nightly-builds
          cache: enable

      - name: Typecheck
        run: juvix typecheck

      - name: Format check
        run: juvix format
